### ISSUE TITLE
Question about the future of Webrecorder Player

### ISSUE THREAD

**Issue by whalehub** [webrecorder/replayweb.page#1]
I've been a big fan of webrecorder.io for a few years now and I've been using your tools Webrecorder Player, Webrecorder Desktop and the command line tool pywb extensively during that time.

The replaying peformance of Webrecorder Player has sadly always been quite bad for me, with complex JavaScript sites taking anywhere from 20-30 seconds to load despite the archive being stored on a local SSD (this was not the case with its predecessor [WebArchivePlayer](https://github.com/ikreymer/webarchiveplayer)).

I gave this new tool a try just now and was blown away by the insane performance difference. The same page that takes over 20 seconds to replay in Webrecorder Player loads in less than two seconds with ReplayWeb.page:

![2020-06-12_05-48-01](https://user-images.githubusercontent.com/44198148/84463183-3b09c780-ac71-11ea-8524-44051303528f.gif)

In light of this, I wanted to ask if there are any plans to deprecate Webrecorder Player the same way it deprecated WebArchivePlayer and to focus development on ReplayWeb.page going forward.

P.S.: Thank you for all the work that you do! I immediately fell in love with the new [embedding](https://replayweb.page/docs/embedding) feature.

**Comment by ikreymer** [comment]
Wow, that is an incredible gif! I knew there were some issues on Windows, but that is quite a difference.

Thanks for finding this new repository! Yes, it is indeed the plan for ReplayWeb.page to replace Webrecorder Player.

We have an announcement planned about all of this in a few hours (probably mid-day your time)
https://webrecorder.net/2020/06/11/webrecorder-conifer-and-replayweb-page.html
https://blog.conifer.rhizome.org/2020/06/11/webrecorder-conifer.html

Do you mind if I use this gif in talking about ReplayWeb.page and some of the changes that it brings?

**Comment by whalehub** [comment]
@ikreymer No, I don't mind you using the gif at all. This is honestly the best day of the year for me so far. I'm passionate about web archiving and these new tools are making me fall in love with it all over again. 😄
