### ISSUE TITLE
integration with ssb

### ISSUE THREAD

**Issue by av8ta** [webrecorder/replayweb.page#101]
Hi @ikreymer raising this issue before making a pull request as advised in the readme.

I found there were just a couple of small changes needed. The wabac.js HttpRangeloader almost worked apart from leaving off the last byte in the wacz archive. Seems all the bytes are needed!

Changed the pattern in chooser.js in this repo to include ssb:// 

SSBRangeLoader in wabac.js is a copy of the http range loader with this one line changed to remove the -1

```js
headers.set("Range", `bytes=${offset}-${offset + length - 1}`);
```

This was necessary because the http range loader broke if I removed the -1 and tried an http url. Later this ssb range loader can be extended with a fallback http url to an online ssb pub that serves wacz files. Then ssb archives will work in conventional browsers as well.

The one change I'm not super happy with, is a hacky fix that we can discuss a better solution; also in wabac, [loaders.js](https://github.com/av8ta/wabac.js/blob/f1c6f7e8c261ce345192194c323082161eb433ce/src/loaders.js#L551) I added this line to append the wacz file extension to ssb blob `sourceName` so that the correct loader is called:

```js
if (config.loadUrl.includes("ssb://")) config.sourceName = `${config.sourceName}.wacz`;
```

Since there are quite a few moving parts, I've put together a [meta repo](https://github.com/av8ta/replayweb-agregore-ssb) to pull together replayweb.page, wabac.js, agregore, and ssb-fetch to clone them all, install dependencies, and yarn link them. It also spins up a testnet ssb server and uploads a wacz test blob so you don't need ssb installed.

To try it out:

Terminal 1 sets up meta repo and starts webpack dev servers for wabac.js and replayweb.js

```bash
npx meta git clone git@github.com:av8ta/replayweb-agregore-ssb.git
cd replayweb-agregore-ssb
yarn bootstrap
yarn start:dev
```

Terminal 2 runs ssb and publishes wacz blob

```bash
yarn ssb
```

terminal 3 runs agregore

```bash
yarn start
```

Agregore browser will start, then browse to <http://localhost:9990>
and paste in ssb://blob/sha256/d8CiqahzsXOJP2xb-Mri8uDAo8351ZnfAd4PmvaWu4Q=

**Comment by ikreymer** [comment]
Thanks for this! I'll have a closer look soon when I have more time!

For the wabac.js changes, probably best to start with a PR there and can discuss the exact changes needed through that.

Hopefully can find a way to resolve the remaining small issues.

**Comment by av8ta** [comment]
I've opened a pull request opened in wabac.js. I'll leave this issue open prior to opening a pull request here.

**Comment by ikreymer** [comment]
With the release of wabac.js 2.12.0 + replayweb.page 1.6.0 which has support for non-http fetch and the UI fix, marking this done!

**Comment by av8ta** [comment]
Awesome :)
