### ISSUE TITLE
WACZ integrity in UI (Archive Receipt UI)

### ISSUE THREAD

**Issue by benhylau** [webrecorder/replayweb.page#113]
WACZ files are authenticated archives with authsign signatures. I'd like the player on replayweb.page and any embedded versions to have:

1. An icon to indicate that a cryptographic signature exists in the WACZ
1. Indication that the content rendered in the player is consistent with the signature in the WACZ
1. The signing domain of the WACZ

This can be a lock icon, for example, that shows up green when signature verifies and turns into a red warning sign when the content has been tampered with. When clicked on, more info such as the datetime of the signature and the signing domain should be displayed.

**Comment by ikreymer** [comment]
Still working on the exact interface with @Shrinks99, but here's a very first pass:

<img width="880" alt="Screen Shot 2022-08-23 at 7 16 18 PM" src="https://user-images.githubusercontent.com/1015759/186302879-e9425433-9d73-4224-bd12-8d435c6f5462.png">


There's probably three different stages of verification we should include, in order of strength:
1) no signature data in WACZ / not WACZ
2) signature data, but [signed anonymously](https://specs.webrecorder.net/wacz-auth/0.1.0/#anonymous-signing) via ArchiveWeb.page
3) signature data, but [signed via trusted observer](https://specs.webrecorder.net/wacz-auth/0.1.0/#domain-ownership-identity-signed-timestamp), via Browsertrix Cloud/authsign

And:
1) All hashes loaded validate
2) All hashes loaded do not validate.
Possible to also include how many hashes have been validated (which will increase as more URLs are loaded).

**Comment by Shrinks99** [comment]
Haven't kept up with this issue 😅 

Just for tracking, here's a pic of the current mockup for the Archive Receipt UI that will appear above embedded tweets and things.

<img width="1095" alt="Screen Shot 2022-09-15 at 4 34 25 PM" src="https://user-images.githubusercontent.com/5672810/190503454-ae7c8908-ae7c-4df8-8263-cb2718cb8dfb.png">

When hashes don't check out the bar looks like this:

<img width="1159" alt="Screen Shot 2022-09-15 at 4 35 15 PM" src="https://user-images.githubusercontent.com/5672810/190503608-50d395c1-e891-4ec8-9dd5-701c31e5d92b.png">

For the AP article implementation (where the witness cert may be either self signed or signed from a domain) we aren't including a mid-level state of authenticity feedback.  This may change at some point in the future.

**Comment by ikreymer** [comment]
Released in 1.7.0!
