### ISSUE TITLE
Switch to auto-js-ipfs in Electron app?

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/replayweb.page#122]
Currently, the electron build uses IPFSClient from wabac.js, but with the change over to auto-js-ipfs (webrecorder/wabac.js#80),
the electron app should probably also use auto-js-ipfs, eg. replacing: https://github.com/webrecorder/replayweb.page/blob/main/src/electron-replay-app.js#L34

I suppose this should also launch a local js-ipfs or go-ipfs client, either separately or as part of auto-js-ipfs?

**Comment by RangerMauve** [comment]
I think using go-ipfs to set up a local kubo daemon is the way to go. Then auto-js-ipfs can connect to it and we can keep more of the code clean.

Also gonna add a step to detect a kubo daemon before making a new one.

**Comment by ikreymer** [comment]
Yeah, I think that makes sense.

Currently, there is a custom js-ipfs node created in electron-replay-app.js, and also essentially a custom, lite ipfs gateway, for detecting http requests that should be loaded from IPFS.

In the browser, this logic can be removed, I think:
https://github.com/webrecorder/replayweb.page/blob/main/src/loader.js#L167

and in the electron app, all that's needed is to start the kubo daemon if not running..

**Comment by RangerMauve** [comment]
Actually, I think it might be cool to add Agregore's IPFS protocol handlers to the app, and then auto-js-ipfs can detect their presense and use them.

I could set up Kubo within the handler lazily

**Comment by RangerMauve** [comment]
Closed by #123

**Comment by ikreymer** [comment]
Released in 1.7.0!
