### ISSUE TITLE
Browser permission confirmation button

### ISSUE THREAD

**Issue by thorsted** [webrecorder/replayweb.page#130]
Running 1.7.0 on Mac OS 10.4.6, loading some warc files this pop-up displays and button does nothing.

![Screen Shot 2022-10-05 at 8 28 48 AM](https://user-images.githubusercontent.com/213296/194086589-e63e232e-6615-4972-b839-d5ee3f9092b6.png)

**Comment by ikreymer** [comment]
This is the ReplayWeb.page App, right?
Can confirm I'm seeing this as well - this should only ever show up in the replayweb.page web-based viewer, taking a look.

**Comment by ikreymer** [comment]
Should be fixed in 1.7.1!
