### ISSUE TITLE
Upload form on mobile

### ISSUE THREAD

**Issue by rebeccacremona** [webrecorder/replayweb.page#14]
On mobile, [`input#filename`](https://github.com/webrecorder/replayweb.page/blob/main/src/chooser.js#L128) escapes its container and the overflow is cut off. As well, since [`button[type="submit"].is-hidden-mobile`](https://github.com/webrecorder/replayweb.page/blob/main/src/chooser.js#L137), so far as I can tell, there is no way to submit the form from a mobile device, unless that device is using an external keyboard.

I spent a few minutes trying to fix while working on the aforementioned accessibility PR, but it was proving sufficiently finicky that I decided to make an issue instead. Might take another swing at it in a bit.

**Comment by ikreymer** [comment]
Thanks for reporting! The overflow cut-off should be fixed now. The field should submit on pressing enter on a mobile keyboard even without the button visible, but do you think that's not clear enough and should still show the button below?

**Comment by Shrinks99** [comment]
Fixed in #295
