### ISSUE TITLE
Angular app not loaded

### ISSUE THREAD

**Issue by iloverails** [webrecorder/replayweb.page#142]
Encountered such a problem that when trying to archive and play an angular website it's not loading properly. I tried with this site https://vggm.nl/ . Here is replayweb archive https://drive.google.com/file/d/1kMsV2n4z7KkTRN5EKMGCSWezIa91vHhV/view?usp=share_link . Can you help me understand please why it's not working?

**Comment by ikreymer** [comment]
Fixed via #143, released in replayweb.page 1.7.9
