### ISSUE TITLE
Error: Expected ./replay/sw.js to have javascript content-type, but received text/plain

### ISSUE THREAD

**Issue by mmjohansson** [webrecorder/replayweb.page#149]
Hello,

When trying to follow the [embedding guide](https://replayweb.page/docs/embedding) I end up with the following error:

![bild](https://user-images.githubusercontent.com/56579809/214789574-a818776e-bd09-4255-95e2-811b2b73dd4f.png)

**my-web-archive-embed.html** (http://localhost:8000/my-web-archive-embed.html)
```
<!DOCTYPE html>
<html>
<body>
<script src="https://cdn.jsdelivr.net/npm/replaywebpage@1.7.11/ui.js"></script>
<replay-web-page source="https://replayweb.page/docs/assets/tweet-example.wacz" url="https://oembed.link/https://twitter.com/webrecorder_io/status/1565881026215219200"</replay-web-page>
</body>
</html>
```

**sw.js** (http://localhost:8000/replay/sw.js)
`importScripts("https://cdn.jsdelivr.net/npm/replaywebpage@1.7.11/sw.js");`

What am I missing? Any help would be greatly appreciated!

**Comment by ikreymer** [comment]
The error is that the web server is returning the wrong content type for the sw.js file.
What web server are you using to serve the files?
The web server needs to return `Content-Type: text/javascript` for the sw.js file, but seems like its returning `Content-Type: text/plain` instead. This should be easy to configure in most web servers, and some do this automatically when they encounter a `.js` file.
We could probably mention this in the guide.

**Comment by mmjohansson** [comment]
Turns out you were right. When switching web server to a Tomcat it worked fine!

One thing that I forgot to mention was that I tried renaming/removing the sw.js file and still got the same error message, so that got me thinking that the error message itself perhaps could be wrong.

Thanks for getting back to me anyways! Closing the issue now.
