### ISSUE TITLE
404 in docs at /troubleshooting

### ISSUE THREAD

**Issue by stavares843** [webrecorder/replayweb.page#150]
STR:
- go to https://replayweb.page/docs/troubleshooting
- where it says ''This is currently possible by using the wacz python library, see [py-wacz documentation](https://github.com/webrecorder/wacz-format/tree/main/py-wacz) for more info.'' 

the https://github.com/webrecorder/replayweb.page/blob/main/docs/troubleshooting.md?plain=1#L26 returns 404

**Comment by stavares843** [comment]
i can add a PR, is https://github.com/webrecorder/py-wacz the correct URL instead?

**Comment by ikreymer** [comment]
Yes, that's 

> i can add a PR, is https://github.com/webrecorder/py-wacz the correct URL instead?

Yes, that's for finding these
