### ISSUE TITLE
Embedding in a react app

### ISSUE THREAD

**Issue by nelson-liu** [webrecorder/replayweb.page#155]
Hi!

Thanks for the detailed docs, they're really useful. I've managed to get an embedded viewer working a la the examples (i.e., using sw.js and ui.js and writing vanilla javascript / html). Is it possible to construct an embedded viewer as part of a React / other non-static app? For example, I'd like to be able to programmatically construct embedded replayers.

Thanks!

**Comment by ikreymer** [comment]
Sure, there should be no problem with that, the `<replay-web-page>` tag is a web component, and should work well with React. See: https://reactjs.org/docs/web-components.html and if you search online, there should be various other examples online for using web components with react.

You just need to make sure the ui.js script is also added to the page, and the sw.js is served as a static file from your domain.

**Comment by ikreymer** [comment]
As an example in our tools, we use the [Lit framework](https://lit.dev/), which in some way is similar to react, in Browsertrix Cloud to dynamically add the embed:
https://github.com/webrecorder/browsertrix-cloud/blob/main/frontend/src/pages/org/crawl-detail.ts#L656

**Comment by nelson-liu** [comment]
Thanks, those were exactly the pointers I was looking for!

Also, is there an easy way to automatically set the `url` param when there's only one page in a `wacz`? I'd like it to skip the initial page list / URL search view in this case.

Thanks once again!

**Comment by nelson-liu** [comment]
I ended up just deciding to always provide the url---thanks again for answering my question.
