### ISSUE TITLE
Page crashes and turns white approximately one second after opening?

### ISSUE THREAD

**Issue by Ecdldaiiere** [webrecorder/replayweb.page#156]
All other sites I've opened so far worked fine, but this wordpress website contained within a .warc file that I'm opening crashes very soon after opening on Replayweb.page program on Windows 10. Not sure what's going on.

**Comment by ikreymer** [comment]
Try in ReplayWeb.page App 1.7.13. Was seeing this with some other files on Mac in 1.7.12, but seems to have been fixed with updating Electron in 1.7.13, if its the same issue.

**Comment by ikreymer** [comment]
Should be fixed with latest release.
