### ISSUE TITLE
Some images not loading on page

### ISSUE THREAD

**Issue by Ecdldaiiere** [webrecorder/replayweb.page#167]
In this archive, https://gofile.io/d/fPRbfB that I opened up using Replayweb.page offline desktop version, the image that should be displayed on the top left corner of this [webpage](https://jstris.jezevec10.com/map/5027) is absent. Why is this? Opening the same .warc file in Webrecorderplayer.exe shows the image.

### Comparison
Replayweb.page
![jMdFpG3](https://user-images.githubusercontent.com/5672810/230180389-ba6c156e-d6b7-458e-a43b-bebf5e7b888e.png)

Webrecorderplayer.exe
![uMea8Iu](https://user-images.githubusercontent.com/5672810/230180418-7c1e3b5e-84b9-48dd-8d35-bc055ad6b833.png)

I know the image is there because I saw it while archiving the page in conifer.rhizome.org, and of course because it also shows in Webrecorderplayer.exe. Is this a bug in Replayweb.page?

**Comment by Shrinks99** [comment]
Interestingly, this isn't actually stored as an "image".  It's a `<canvas>` element that seems to render the graphic.

**Comment by ikreymer** [comment]
Thanks for reporting - this is a bug related to indexing, and will be fixed in an upcoming version

**Comment by ikreymer** [comment]
The issue was a peculiar combination of WARC `revisit` records at the same timestamp that overrode the original `response` record. Added filtering to prevent `revisit` from overriding non-revisits in wabac.js

**Comment by ikreymer** [comment]
Fixed in 1.7.14 - the initial WARC load may be a bit slower initially (will look for ways to optimize in the future), but the images should now appear.
