### ISSUE TITLE
Issues with loading resources from Cloudflare bucket in Firefox 112

### ISSUE THREAD

**Issue by despens** [webrecorder/replayweb.page#168]
This URL prompts replayweb.page to load a wacz file from a public Cloudflare bucket:

https://replayweb.page/?source=https%3A%2F%2Fpub-b9760f4d73dc4047ae381bfcf84702ae.r2.dev%2Fwolf-and-unicorn.wacz

It works fine in Chrome 112, but fails in Firefox 112.

Firefox throws a `TypeError: NetworkError when attempting to fetch resource.`:

![image](https://user-images.githubusercontent.com/571494/231666492-6d8b718e-e7ee-4e4d-9f38-cf268b79dbdd.png)

**Comment by ikreymer** [comment]
I think it is the same issue as mentioned here: https://github.com/webrecorder/replayweb.page/issues/74#issuecomment-1008150240
Firefox has more stringent CORS requirements than Chrome now. Probably if you add `access-control-allow-headers: range` or `access-control-allow-headers: *` it should work.

**Comment by despens** [comment]
Indeed you're right, that did the trick! For anybody having the same issue stumbling across this in the future, here's the CORS policy that worked

```json
[
  {
    "AllowedOrigins": [
      "*"
    ],
    "AllowedMethods": [
      "GET",
      "HEAD"
    ],
    "AllowedHeaders": [
      "*"
    ]
  }
]
```

**Comment by ikreymer** [comment]
Thanks! We've added additional docs for configuring CORS here, which includes this example: https://replayweb.page/docs/cors-settings
