### ISSUE TITLE
archived page isn't replayed

### ISSUE THREAD

**Issue by robert-1043** [webrecorder/replayweb.page#174]
Quite new but persistent error: archived page is shown in search results with excerpt but isn't replayed.

However: a colleague had an error on a page that replayed in my browser (consulting the same wacz on network).  And vice versa...

![image](https://github.com/webrecorder/replayweb.page/assets/41336343/dd472a92-ec41-44e8-adee-a47912d29945)

Closing browser doesn't solve the problem.  Unloading the collection & reloading again solved the issue for this page, but not for another one.

![image](https://github.com/webrecorder/replayweb.page/assets/41336343/274b91d0-fc53-4cde-b2c5-96d43785f6cc)

Some hickup while loading?  While testing the unload/reload I even got an error on the main seeds and all other pages.

**Comment by ikreymer** [comment]
Could you share the WACZ file? It's fairly hard to debug these type of issues w/o a specific example..
Perhaps latest release introduced some sort of regression, hard to say exactly..

**Comment by ikreymer** [comment]
Fixed in RWP 1.8.2
