### ISSUE TITLE
Reproduction warc archives

### ISSUE THREAD

**Issue by steper70** [webrecorder/replayweb.page#180]
After the last update warc archives uploaded to replayweb.page no longer play

**Comment by ikreymer** [comment]
That is not correct, just tested with a few different WARCs which load fine, as before.
If you'd like us to take a look at a specific issue, please provide an example.

**Comment by steper70** [comment]
I made a test acquisition.
This archive is played with version "ReplayWeb.page-1.7.14". However, it does not work with the ReplayWeb.page-1.8.0 version
I attach warc and wacz shared folder link and related screenshots.

[https://1drv.ms/f/s!AtLWnnMaFSeQ6wK69DOK6uoyp2Bc?e=Uj1sJW](url)

**Comment by ikreymer** [comment]
Thanks for the repro! Very oddly, this seems to be related to the latest version of Ruffle, for some reason, this stops loading with Ruffle release >2023-05-13. For now, switching back to that version.
Will open an issue with ruffle.
