### ISSUE TITLE
Unarchived pages which have a Link on an archived HTML Page Result in multiple Self-Redirect (302)

### ISSUE THREAD

**Issue by ARiedijk** [webrecorder/replayweb.page#184]
Replayweb.page version  **1.7.14**:  Works normal behavior, players return error with tell: resource not in archive
Replayweb.page version  **1.7.15**:  Fails, multiple retries, status 302?

<img width="1099" alt="Screenshot-network-tab" src="https://github.com/webrecorder/replayweb.page/assets/89101254/87e373bf-a630-4b95-a8d3-9ad0529e0bf2">

**Given simple HTML in the archive:**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <a href="externalredirect.php">External redirect</a>
</body>
</html>


```
**When click on "External redirect" link **

**Then**
The 'Replayweb.player' Treats it as a Redirect Request - Check Out the Screenshot!
**Expect**
Notification: The Resource is Not Found in the **Archive**
[waczfile-to-test.zip](https://github.com/webrecorder/replayweb.page/files/11799360/waczfile-to-test.zip)

**Comment by ikreymer** [comment]
Thanks for the simple repro, fix is in wabac.js and will be in next release
