### ISSUE TITLE
Show thumbnail screenshots in pages list

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/replayweb.page#199]
### Context
We have thumbnails now and should use them!

### Requirements
- Users can see thumbnails for each page in the pages list to the right of the title and URL if thumbnails are available in at least one of the WACZ files loaded.

## Mockups

![Thumbnails_1](https://github.com/webrecorder/replayweb.page/assets/5672810/8acde24a-3de9-42b6-a716-94dbb4b82c99)

## Todo
- [x] Mockups
- [x] Enable thumbnails during crawling
- [ ] WACZ spec
- [x] UI changes

**Comment by matteocargnelutti** [comment]
Oh cool! Is there a place I can read about how that feature is going to work / works in `pages.jsonl`? Thanks :)

**Comment by Shrinks99** [comment]
@matteocargnelutti Not yet but once this is done hopefully yes!

[We're still working on these tools ourselves!](https://github.com/webrecorder/browsertrix-crawler/issues/247#issuecomment-1503637912) :)

**Comment by Shrinks99** [comment]
Looks closed tp me!
