### ISSUE TITLE
Firefox can't access wacz

### ISSUE THREAD

**Issue by DHKaplan** [webrecorder/replayweb.page#202]
I'm accessing a wacz file on the web via Safari and Chrome (both on macOS), but Firefox (also macOS) gives me the error:  **An unexpected error occured: TypeError: NetworkError when attempting to fetch resource.** The site is: [https://replayweb.page/?source=https://www.wticalumni.com/warc/WTIC.wacz&url=https://www.wticalumni.com/#view=resources&url=https%3A%2F%2Fwww.wticalumni.com%2F&ts=20230718205647](url)

**Comment by ikreymer** [comment]
We've added additional docs for configuring CORS here: https://replayweb.page/docs/cors-settings

**Comment by DHKaplan** [comment]
Thanks for you help. With your previous info I was able to successfully modify my server's settings and my 3 main browsers (Safari, Firefox, Chrome) all work fine. I appreciate your efforts.
