### ISSUE TITLE
Improved support for MultiWACZ / json-based config with multiple WACZ files

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/replayweb.page#208]
Currently, if the file loaded as an embed is a JSON MultiWACZ collection, the UI doesn't quite respond correctly:
- The info tab just shows the name of the file, eg. `replay.json` - it should probably list all the WACZ files
- Total size is size of the JSON, not all of the WACZ files
- Name / description from JSON is not shown
- No way to download all WACZ files as a single WACZ, but can be supported with nested WACZ files.

**Comment by Shrinks99** [comment]
Until we move forward with the dedicated curation page, seems like this sidebar would be a reasonable place to put the name and description from the JSON?

![Screenshot 2023-08-15 170853](https://github.com/webrecorder/replayweb.page/assets/5672810/664f3fe1-5773-486e-85d7-de9ce1bf73a3)

**Comment by Chickensoupwithrice** [comment]
Some work on this: 

![image](https://github.com/webrecorder/replayweb.page/assets/22575913/6d791f95-a2cc-47a9-9e10-5bc7def39997)

![image](https://github.com/webrecorder/replayweb.page/assets/22575913/1fe83502-edf8-4889-a186-e042f7dcf823)

Shows:
- File size of combined WACZ
- List of all WACZ files
- Description and Title from JSON
- Description and Title on pages list as well

**Comment by ikreymer** [comment]
Nice!

I wonder if we should make the WACZ files downloadable links as well?

**Comment by Chickensoupwithrice** [comment]
Yeah, I was thinking exactly that, we already have the source url available so I'm going to do it.
