### ISSUE TITLE
No results for `urn:` prefix or exact search

### ISSUE THREAD

**Issue by SuaYoo** [webrecorder/replayweb.page#220]
Only "Contains" works when searching for a URL prefixed with `urn:`, e.g. `urn:thumbnail:https://example.com/`

To reproduce:
1. Load an archive with favicons or thumbnails.
2. Click "URLs" tab.
3. Enter `urn:` into search bar, leave "Prefix" checked, and hit enter. Observe that no results are found.
4. Check "Contains" and hit enter. Observe that matches are found.

**Comment by ikreymer** [comment]
Should be fixed in 2.0.2 via #334
