### ISSUE TITLE
Archive not loaded

### ISSUE THREAD

**Issue by iloverails** [webrecorder/replayweb.page#229]
I tried to load this archive https://drive.google.com/file/d/1MfTNzcLTVYCVmaOyTBj3BQvKVB12lB1k/view?usp=drive_link there https://replayweb.page/ but no luck, just pending icon, could you help me to understand please why I'm doing wrong?

**Comment by ikreymer** [comment]
This should now be working with latest version. (Suggest downloading locally the WACZ file locally, if loading from Google Drive is too slow as it rate limits requests).
