### ISSUE TITLE
replayweb.page not loading complete WARC-file

### ISSUE THREAD

**Issue by nvanderperren** [webrecorder/replayweb.page#23]
Hi,

I have a WARC-file of 970 MB. I discovered that the full archive is not loaded, not even 1 MB of the archive is loaded. A lot of pages/URL's can't be seen with replayweb.page.

My pages also have no styling. 

<img width="1272" alt="Schermafbeelding 2020-10-14 om 15 18 36" src="https://user-images.githubusercontent.com/17183054/95994851-12692880-0e31-11eb-96ca-675fa89ac597.png">

Maybe I'm doing something wrong? the WARC was created with Heritrix.

**Comment by ikreymer** [comment]
Does the same behavior happen in both the web app and the desktop app versions?
Are you able to load the URLs from the URL search page?
Hard to say what the issue is, would you be able to share this WARC file?

**Comment by nvanderperren** [comment]
In the desktop app it says there are no URL's (#22). In Webrecorder Player everything looks normal:

<img width="642" alt="Schermafbeelding 2020-10-19 om 16 06 12" src="https://user-images.githubusercontent.com/17183054/96462223-9fdbbc80-1225-11eb-84d3-4699d4e2e769.png">

I want to share the WARC. How do I send it to you?

**Comment by ikreymer** [comment]
You can send it to me via email, or let me know if you want a different option: ikreymer [ at ] gmail
