### ISSUE TITLE
Chrome browser crashed when trying to replay a FB archive

### ISSUE THREAD

**Issue by dteyssou** [webrecorder/replayweb.page#230]
Chrome browser (version 116.0.5845.140 on MacOs Ventura 13.4.1) crashes when trying to replay a FB page archive recorded with webrecorder extension. 
The crash occurs when using replayweb within the webrecorder plugin. The website replayweb.page works with the same files.

**Comment by ikreymer** [comment]
This is really a duplicate of webrecorder/archiveweb.page#194 and has been fixed there.
