### ISSUE TITLE
Show archive info in modal

### ISSUE THREAD

**Issue by SuaYoo** [webrecorder/replayweb.page#235]
### Changes
- Show archive info in modal dialog, similar to RWP info modal
- Add location bar dropdown menu item to open archive info

### Mockups
[Archive Info Dialog Popup](https://www.figma.com/file/M5ZLsZNgK15RWzZF1SeoTM/ReplayWeb.Page-2.0-UI?type=design&node-id=645%3A8116&mode=design&t=gnrTUGCxNsvMttbx-1)

**Comment by SuaYoo** [comment]
@Shrinks99 could you drop in most up to date mockups here?

**Comment by Shrinks99** [comment]
[Mockups for Archive Info Dialog](https://www.figma.com/file/M5ZLsZNgK15RWzZF1SeoTM/ReplayWeb.Page-2.0-UI?type=design&node-id=645%3A8116&mode=design&t=gnrTUGCxNsvMttbx-1)

**Comment by emma-sg** [comment]
Closed by #258
