### ISSUE TITLE
Player keeps loading on a 404 page

### ISSUE THREAD

**Issue by borsboomm** [webrecorder/replayweb.page#245]
When you navigate to a page that has a 404 response code the player keeps spinning instead of showing a "this page can not be found in this archive"

In the attached wacz there are 2 crawls:

- **Time stamp 1 - 9/22/2023, 11:10:10 AM**:  /linktodeleted.php links to a page that has a 200 status code and everything works as expected

- **Time stamp 2 - 9/22/2023, 11:11:42 AM**: /linktodeleted.php links to a page that has a 404 status code and the player keeps spinning.

Version tested: v1.8.12 both stand alone and online version

[404.zip](https://github.com/webrecorder/replayweb.page/files/12699356/404.zip)

**Comment by ikreymer** [comment]
The spinner will now stop after a few seconds. The standard 404 page is shown if the URL does not exist in the archive at all. However, in this case there is a 404 page in the WACZ file, it is just blank. This is what the user would see in the browser, so it seems correct to show the blank page as that is what was served by the web server.
We could replace blank pages with an error message, but that seems less accurate than just replaying the empty page as is.
