### ISSUE TITLE
[Replay Bug]: Failure to render websites published on Microsoft SharePoint

### ISSUE THREAD

**Issue by iholliew** [webrecorder/replayweb.page#273]
### ReplayWeb.page Version

v1.8.14

### What did you expect to happen? What happened instead?

I’ve encountered an issue trying to 'replay' content published our Microsoft SharePoint intranet site in ReplayWeb.page. The link to the SharePoint site looks like it's been captured correctly, but the content on the pages isn’t loading. The content does appear for a few seconds before vanishing. The site requires users to verify their identity through Okta, a single sign-on service, but I haven't encountered any issue recording other sites that use Okta (e.g. Workday). I’ve only been able to successfully render the page using the ‘Chrome v76’ browser option in Conifer. 

### Additional details

A video demonstrating the issue, a screenshot of what the content should look like, and a .wacz file have been provided to info@webrecorder.net. They can't be shared here because of business sensitivity.

**Comment by ikreymer** [comment]
Sharepoint replay should now be fixed/much improved in 2.1.1 release!

**Comment by iholliew** [comment]
Brilliant, thanks @ikreymer!
