### ISSUE TITLE
[Bug]: Safari can't open wacz stored on Dropbox, Firefox & Chrome can

### ISSUE THREAD

**Issue by DHKaplan** [webrecorder/replayweb.page#274]
### ReplayWeb.page Version

v1.8.14

### What did you expect to happen? What happened instead?

I was trying to open a wacz file in Safari, instead received the message: _"An unexpected error occured: TypeError: Load failed", "Try Again"  "Back"_ 

The link I was trying to open in Replayweb.page was 
[https://dl.dropboxusercontent.com/scl/fi/y5i6flnz9qkgx0ysxv1fa/2023-12-25-WTIC.wacz?rlkey=ot7x29seq7za8ks4avpyzgayo&dl=0](url)

This link DOES open in Firefox and Chrome. I'm running on macOS Sonoma 14.2.1 on an M3 iMac

### Step-by-step reproduction instructions

1. Load Replayweb.page
2. Enter the link above
3. Hit "Load"

### Additional details

Works fine in the Replayweb.page.app on macOS

**Comment by Shrinks99** [comment]
This is a Safari / Dropbox issue.  Safari's CORS rules are stricter than Firefox's or Chrome's.  For details see [this page](https://replayweb.page/docs/cors-settings#differences-between-chrome-and-firefox-and-safari).
