### ISSUE TITLE
loading stalls on larger WARC files

### ISSUE THREAD

**Issue by marklevit** [webrecorder/replayweb.page#29]
I am trying to load files that are between 273 MB and 2 GB.  I am using a Mac.  However, the files stall halfway through when loading.  I do not have this issue with small files.  These are WARC files that were created using Conifer.

**Comment by cfeddersen** [comment]
I experience a similar issue with a file about 5GB in size. I'm using the latest Chrome on mac. Maybe a red herring, but having the developer console open seems to improve the situation. It regularly outputs the number of loaded entries. Maybe that helps. Chrome is faster than Firefox to load files.

**Comment by ikreymer** [comment]
@cfeddersen if having devtools open has helped, a recent change might have fixed things (possibly the service worker was not waiting for the full load to complete). Could you try again with latest version on replayweb.page / app 1.3.10?

**Comment by ikreymer** [comment]
Additional fixes in 1.3.11 now ensure that the serviceworker stays active while loading, which seems to especially help in Firefox. I believe this should work now, but please comment if you are still seeing issues with larger WARCs.

I haven't tested with WARCs as big as 5GB, it will need to load (but not store) the entire WARC to generate an index, so it may take some time, but I believe it should finish, eventually. Converting to WACZ is still the recommended approach, hope to make that process easier soon
