### ISSUE TITLE
WARC from authenticated session redirects to logout page

### ISSUE THREAD

**Issue by dlitz** [webrecorder/replayweb.page#30]
I have a WARC file from a logged-in site that I generated using Webrecorder Desktop, and which replays correctly in Webrecorder and Webrecorder Player.

In replaywebpage, something (presumably JavaScript from the archive) is attempting to redirect to the logout page of the site, instead of displaying the original data from the archived session:

    Sorry, the URL https://app.docusign.com/logout is not in this archive.

I've attached a sample .warc file (generated using a dummy account) for reproducing this bug.

### Sample WARC file:
[5nntovqatoa4bbxh-20201230001405.warc.zip](https://github.com/webrecorder/replayweb.page/files/5752664/5nntovqatoa4bbxh-20201230001405.warc.zip)

Click the "Bug Demo" bookmark.

### What I expect to see:
Archived page is shown.
![screenshot-ok-webrecorder-player-1 8 0](https://user-images.githubusercontent.com/99377/103323231-c02eb100-49f6-11eb-9f92-530ea9898cf0.png)

### What I actually see:
    "Sorry, the URL https://app.docusign.com/logout is not in this archive."
![screenshot-bad-replaywebpage-1 3 4](https://user-images.githubusercontent.com/99377/103323233-c329a180-49f6-11eb-9391-e4224cee5dd7.png)

### Software/Versions tested:
* OS: Debian GNU/Linux unstable (amd64)
* [ReplayWeb.page-1.3.4.AppImage](https://github.com/webrecorder/replayweb.page/releases/download/v1.3.4/ReplayWeb.page-1.3.4.AppImage)
* [webrecorder-player-1.8.0.AppImage](https://github.com/webrecorder/webrecorder-player/releases/download/v1.8.0/webrecorder-player-1.8.0.AppImage) -- For "expected" screenshot.
* [webrecorder-2.0.3.AppImage](https://github.com/webrecorder/webrecorder-desktop/releases/download/v2.0.3/webrecorder-2.0.3.AppImage) -- Used to create the WARC file.
* I also tried the web version today (2020-12-29) at <https://replayweb.page>, in both Chrome and Firefox.  I did not notice any significant difference in behaviour compared to the AppImage version.

**Comment by ikreymer** [comment]
Sorry for taking long to get to this, I think it should now work in the latest replayweb.page, and will be in the upcoming 1.3.10 release. (The issue was the Set-Cookie header was not being replayed using the existing cookie preset injection system and no Cookie header on the request).

**Comment by ikreymer** [comment]
Closing as I believe this should now be fixed!
