### ISSUE TITLE
[Replay Bug]:  archived reddit pages not displaying properly

### ISSUE THREAD

**Issue by hamoudak** [webrecorder/replayweb.page#317]
### ReplayWeb.page Version

v 0.11.3

### What did you expect to happen? What happened instead?

I have archived some reddit pages and i was trying to test replaying with view recorded page. I found no display at all, just a white page and some pages open portion of the post then reloads to solid white page ? I don't know how to get these pages as any website ? could you explain to me what to do or what's happening ?

* another issue related to the first one is that Facebook pages not displaying except the first posts then stop loading next posts .

![chrome-extension___fpeoodllldobpkbkabpblcfaogecpndd_replay_index html_source=local%3A%2F%2Fwjhaaivep7gruslitgogg (1)](https://github.com/webrecorder/replayweb.page/assets/155604457/d48cf287-3930-4036-8659-87e939d3f410)
<img width="960" alt="portion_of_the_topic" src="https://github.com/webrecorder/replayweb.page/assets/155604457/a6978cec-1a86-45e9-a9b4-4befb4f2d2b6">
![chrome-extension___fpeoodllldobpkbkabpblcfaogecpndd_replay_index html_source=local%3A%2F%2Fwjhaaivep7gruslitgogg](https://github.com/webrecorder/replayweb.page/assets/155604457/197a02f3-42d7-49fb-8564-85b3d3839fe9)

**Comment by ikreymer** [comment]
Reddit issues should be fixed in 2.0.1

**Comment by hamoudak** [comment]
It worked but there's something with loading the pages. it reloads very slow , it takes about 15 second to open on windows 10 .
<img width="956" alt="slow reloading" src="https://github.com/webrecorder/replayweb.page/assets/155604457/a6c56bad-be8c-4d14-8488-e0ddfccdfa1b">


<img width="956" alt="after-reloading" src="https://github.com/webrecorder/replayweb.page/assets/155604457/6a5f9295-75ee-4d00-b494-8f852d3c5011">
