### ISSUE TITLE
[Replay Bug]: Ebay carousels broken

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/replayweb.page#326]
### ReplayWeb.page Version

v2.0.0

### What did you expect to happen? What happened instead?

On live ebay listings, interacting with the carousel's expand button opens the images in a larger view taking up the whole screen.  Clicking on any images that aren't the cover image will open those ones.

On archived copies, clicking this does nothing 

### Step-by-step reproduction instructions

1. Archive an ebay listing page with ArchiveWeb.page.  Click through the carousel and open in full screen to load the full res versions of the pictures.
2. Open the WACZ in ReplayWeb.page.  Verify that the images, both thumbnails and full res versions are in the archive.
3. Attempt to view all the images on the listing.

**Comment by ikreymer** [comment]
Fixed in 2.0.1
