### ISSUE TITLE
[Replay Bug]: When I open a specific archive, the software becomes unresponsive and turns white

### ISSUE THREAD

**Issue by cpqcat** [webrecorder/replayweb.page#330]
### ReplayWeb.page Version

v1.8.17

### What did you expect to happen? What happened instead?

It should be that When I open the archive, the webpage should be accessible and operable.
But when I open a specific archive, the software becomes unresponsive and then turns white

web archive and picture :
[teramind2.zip](https://github.com/user-attachments/files/15807557/teramind2.zip)
unresponsive picture:
![unresponse](https://github.com/webrecorder/replayweb.page/assets/43975530/f0c73f54-bbd6-4e47-b20a-02d21eb88d21)
white page picture:
![white_page](https://github.com/webrecorder/replayweb.page/assets/43975530/a84834ba-3d14-4575-beed-2dd9689d1092)

origin website: https://democompany.teramind.co/#/report/Focus+Dashboard

**Comment by ikreymer** [comment]
Appears to be an issue that can be fixed via wombat, will be in 2.0.2 release.
