### ISSUE TITLE
[Replay Bug]: Browser Crashing & Embedded Video Issues for Arc GIS Storymaps

### ISSUE THREAD

**Issue by steinburgb** [webrecorder/replayweb.page#332]
### ReplayWeb.page Version

v2.0.2

### What did you expect to happen? What happened instead?

Working on a strategy for capturing 'storymap' student projects hosted by Arc GIS -- rich single-page sites. Currently running into two issues with them:

1. Trying replay WACZs of storymaps using ReplayWeb.page in Chrome consistent crashes the browser. Firefox has not given this issue thus far.
-- This occurs as soon as you open the site's main page

2. If the storymap contains an embedded Youtube/Vimeo video, when that embedded video would be loaded, the replay of the site "whitescreens" instead. 
-- This occurs when scrolling down the page, just a bit above the location of the embedded video in the live version of the storymap

I have two examples of this on hand, one with an accessible live version of the storymap and the other without:

**Example WACZ File:** 
**URL:** https://storymaps.arcgis.com/stories/ba4f5e7f25034e4baaf29c88338147d0
**WACZ:** https://utoronto-my.sharepoint.com/:u:/g/personal/bennett_steinburg_utoronto_ca/EcA-Ulc6_1lIj79d51DFk9gBZTvmzcOl9IgMr04LdVfFxw?e=7DNiYa

**Example archive hosted on one of our sites (live counterpart unavailable):**
https://collections.digital.utsc.utoronto.ca/test.html

### Additional details

Part of this issue originally flagged here: https://forum.webrecorder.net/t/media-capture-crashing-embedded-videos-in-arcgis-storymaps/618/2

**Comment by ikreymer** [comment]
@steinburgb this is fixed in 2.0.2. Unfortunately, do to how that youtube embed is set up, it's almost impossible to get it to load due to a race condition. However, the page should otherwise load and not crash or white-screen.
