### ISSUE TITLE
[Feature]: Additional navigation events for embeds

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/replayweb.page#333]
### Context

Add a way to send events to containing page when a <replay-web-page> embed:
- starts navigating to a new page
- finishes navigating to a new page
- gets a 404 when navigating to a new page.

### What change would you like to see?

This will make integration into the Browsertrix QA system more robust (per webrecorder/browsertrix#1780) and can be used by other tools integrating RWP as well.

**Comment by Shrinks99** [comment]
Should update ReplayWebpage docs!  @ikreymer
