### ISSUE TITLE
How to make a WARC searchable

### ISSUE THREAD

**Issue by brechtm** [webrecorder/replayweb.page#35]
I noticed that the netpreserve-twitter.warc example file has a list of pages and that it's possible to perform a full-text search on these pages. A WARC of a site created by wget doesn't have any pages defined and cannot be searched. I was hoping to somehow make this WARC searchable, but I have not succeeded in doing so. I tried converting the WARC to a WACZ using py-wacz, but the resulting WACZ file behaves exactly like the WARC file in repayweb.page.

I understand this is not really an issue with replayweb.page, but I was expecting to be able to use it's page search functionality on my WARC file just like with the example file. I've searched the net for information on creating a searchable WARC, but nothing has turned up.

**Comment by ikreymer** [comment]
Hi, thanks for asking, this is a good question, and something we should document better!

The WARC format has no standardized way to store pages or full text data, and so previously the page definition was baked into the WARC in a non-standard way as JSON in the `warcinfo` record. You can see this in the netpreserve-twitter.warc example.
ReplayWeb.page than actually does text extraction on the fly, but only for these pre-defined pages.
But this approach is not recommended.


With the WACZ format, the idea is to standardize the page list in a more manageable way, and to allow for adding the extracted text to the page list in a simple newline-delimited JSON file.

If you're converting a WARC to WACZ with py-wacz, you have two main options:

1. If you know what the pages are and want full control, you can provide a partially filled in `pages.jsonl` file, eg:

```
{"url": "https://example.com/page1"}
{"url": "https://example.com/page2"}
```

and then specify it with the `-p <pages.jsonl>` flag.

2. You can let `py-wacz` autodetect which URLs that are pages, with the `--detect-pages` option. This may detect some false positives, though.

That gives you the pages when creating the WACZ. To include the text, which is also auto-extracted from the HTML, you can add the `-t` flag, which will have py-wacz parse the HTML and extract text. If you run into any issues with this, definitely open an issue on the [wacz-format](https://github.com/webrecorder/wacz-format) repo.

And for option 1, another variation is that you can actually even pre-fill the text as well if it was extracted in some other way, and fill it in via `{"url": "https://example.com/", "text": "..."}`. For now, py-wacz simply uses boilerpipe3, but perhaps other options can be supported in the future (eg. rendering in the browser).

Hope this helps!

**Comment by brechtm** [comment]
In my case I'm archiving a Discourse forum with hundreds of posts, so manually listing the pages is not an option.

I did use both the _--text_ and _--detect-pages_ options, but they didn't seem to make a difference (no pages, no full-text search). Upon trying again now, py-wacz printed "Num Pages Detected: 571" during the conversion and pages _are_ present now! I'm not sure what went wrong yesterday. I tried to reproduce the issue but failed (different order of options, .warc.gz input vs .warc). I must simply have been confused with all the WARC and WACZ files in that directory.

Thanks for motivating me to try again :-)

**Comment by ikreymer** [comment]
Great! Glad that it worked! Perhaps something to discuss over at wacz-format, but can think about if there's anything that can be done to make the process easier for those creating WARCs via wget and then generating WACZ from those..

**Comment by brechtm** [comment]
There's plenty of information out there on how to create WARCs with wget. I just had a hard time finding how to make it searchable. I eventually ended up with py-wacz, but from it's documentation it wasn't clear this would produce a searchable WACZ.
