### ISSUE TITLE
[Replay Bug]: Images are not being displayed in replay webpage (or in conifer)

### ISSUE THREAD

**Issue by webarchive21** [webrecorder/replayweb.page#351]
### ReplayWeb.page Version

v2.1.1

### What did you expect to happen? What happened instead?

Hey,

When I try to archive the seed https://www.roeenegri.com/moments-with-roee most of the images are not being displayed in replay web page (I attached a PNG file that demonstrate how it looks in replay web page):
<img width="927" alt="roeenegri site" src="https://github.com/user-attachments/assets/13302f5d-09e5-4885-8c61-3b84e96859e0">

I also attach the warc file: [roeenegricom-20240630063529.warc](https://nli-my.sharepoint.com/:u:/g/personal/roi_zarfati_nli_org_il/EcxdjAzL2CBOn-M9HoYNXfYBkNvTgLTPV_6KjSY8ZmzaOw?e=Z0SQHU)
Can it be fixed?

Best,
Roi

**Comment by ikreymer** [comment]
It looks like the images were not captured correctly - it looks like the WARC was created using an older version of Webrecorder tools. We recommend using [ArchiveWeb.page](https://archiveweb.page/) Extension or App, trying it there it should work.
