### ISSUE TITLE
embedding and service workers path

### ISSUE THREAD

**Issue by atomotic** [webrecorder/replayweb.page#36]
from [doc](https://replayweb.page/docs/embedding):

```Thus, if the HTML snippet was added to https://my-site.example.com/path/my-web-archive-embed.html then the sw.js should be added such that it is at: https://my-site.example.com/path/replay/sw.js.```

i have this example: https://docuver.se/replayweb/mlol-iiif-stories.html

the sw in this path is not working https://docuver.se/replayweb/replay/sw.js

> ui.js:199 Error during service worker registration: TypeError: Failed to register a ServiceWorker for scope ('https://docuver.se/replay/') with script ('https://docuver.se/replay/sw.js'): A bad HTTP response code (404) was received when fetching the script.

while it works if saved on https://docuver.se/replay/sw.js

**Comment by edsu** [comment]
I noticed this as well. Thanks for documenting it @atomotic!

**Comment by ikreymer** [comment]
Should be fixed in 1.3.10!
