### ISSUE TITLE
Local WARC file stuck at loading

### ISSUE THREAD

**Issue by laurelin88** [webrecorder/replayweb.page#4]
Hi, thank you for your new and/or updated tools, this has been a very exciting day after your announcement! :)

I attempted to load a WARC from my machine on the website but it keeps getting stuck either at 15% or at 23%. The WARC file is relatively big (18MB), but not unreasonably so. It was made using the latest release of the Webrecorder Desktop app on Mac.

**Comment by whalehub** [comment]
Are there any errors in the browser's developer console (you can open it with `F12` or `CTRL+SHIFT+I`)? I loaded a 2GB WARC file on the website earlier today and it only took a few seconds  for it to load since everything is done locally.

**Comment by ikreymer** [comment]
@laurelin88 What browser are you using? I've seen this happen in Firefox, but not in Chrome.. Chrome seems to load significantly faster as well, looking into this to see why..

**Comment by laurelin88** [comment]
Apologies for the late reply, I was just able to look into this again and indeed the file seems to load without any problems on Chrome but not on Firefox. Thank you!

**Comment by ikreymer** [comment]
@laurelin88 The latest release has several optimizations for local files. I believe that WARC getting stuck issue should be fixed now. Let me know if you get a chance to test.

**Comment by laurelin88** [comment]
@ikreymer Hi Ilya, thanks for the update - it's working like a charm, just tested with multiple WARCs on Firefox and Chromium.

**Comment by ikreymer** [comment]
Great! Closing this as fixed!

**Comment by code-Yking** [comment]
It's my first time using this website and it is getting stuck. It happened twice already with a 340 mb WARC file at 28% and 11%. I am using Chrome in a Windows machine.
