### ISSUE TITLE
Issue with rendering images in existing WARC files

### ISSUE THREAD

**Issue by jakebickford** [webrecorder/replayweb.page#5]
Hello and congratulations on all the new developments with the webrecorder tools.

I was trying out replayweb.page compared to the old Web Recorder Player, and the performance seems much improved. However, it looks like some images are not rendering for me in replayweb.page where they were working in the old player. 

For example, here they are in the old player:
![image](https://user-images.githubusercontent.com/67007698/85580374-93f33b80-b633-11ea-8f26-b7350f47d711.png)

And here is the same page in the new one:
![image](https://user-images.githubusercontent.com/67007698/85580460-ab322900-b633-11ea-87ec-b63113cc34fd.png)

I am using the desktop application of both webrecorder player and replayweb.page, running in Windows 10. 

Many thanks for all your work on this project.

**Comment by ikreymer** [comment]
Thanks for reporting, think I have a repro of this, will take a look.

**Comment by ikreymer** [comment]
@jakebickford try again now, I think the issue should be fixed with latest update. You may have to reload the WARC but may just work as is.

**Comment by jakebickford** [comment]
@ikreymer thanks very much for looking at this. The images are now rendering but they seem to be at a lower resolution than in the old player. I have tried reloading the WARC and it doesn't seem to make a difference. This time I am using the web-based app rather than the installed application as the releases page appears to be down, so I don't know if that's a possible explanation.

Old player:
![image](https://user-images.githubusercontent.com/67007698/85834121-bea3d800-b78a-11ea-8827-0519525ab295.png)

ReplayWeb.page
![image](https://user-images.githubusercontent.com/67007698/85834171-d2e7d500-b78a-11ea-94d0-fa9f1cc01f88.png)

**Comment by ikreymer** [comment]
Thanks for finding that as well! Should be fixed now on https://replayweb.page, and will be in next update of the app as well once things look good.

**Comment by jakebickford** [comment]
Brilliant, thanks @ikreymer, confirm this is now looking good at my end.

Many thanks!

Jake
