### ISSUE TITLE
Collection loading stalls.

### ISSUE THREAD

**Issue by jswrenn** [webrecorder/replayweb.page#6]
The collection referenced in https://github.com/webrecorder/pywb/issues/573 also causes replayweb.page to struggle. It takes over five minutes before the message `Indexed 1234014 records` is printed. Immediately thereafter, this warning is printed to the console:
```
DOMException: Transaction timed out due to inactivity.
```
My browser tab crashes soon thereafter. I'm using Chrome 80.0.3987.122, Linux.

**Comment by ikreymer** [comment]
Yeah, at this scale (30GB+), it won't be able to load it all with just the WARC.
It needs to be converted into a WACZ collection with a compressed index, and then it can load the collection on-demand.
I don't quite have the tools ready to do this, but the idea is that it could take a pywb collection and create a compressed .wacz file as per: https://github.com/webrecorder/web-archive-collection-format

I'll try to have a skeleton of a tool that does this (for the current spec) fairly soon, if you want to try it out.

**Comment by jswrenn** [comment]
Ah, sorry I should have clarified: I packaged the collection as WACZ before attempting to load it into replayweb.page.

**Comment by ikreymer** [comment]
Ah ok! But just using the plain, uncompressed .cdx, right? WACZ supports both compressed and uncompressed
The compression part is rather straightforward, just need to have a script that does it.. I've been using the one on webarchive-indexing but its a bit old..

**Comment by Argon-** [comment]
@ikreymer is there a solution for this?
I use grab-site to create large, singular warc files (with uncompressed .cdx) and just noticed that ReplayWeb is not able to open these. Previously I only tested with smaller archives. Is there a way to convert my existing warc archive to a WACZ collection?

**Comment by ikreymer** [comment]
Yes, would recommend using WACZ for larger warcs due to browsers issue having to load the entire file into memory at once. Firefox I know still seems to lock up randomly when streaming a larger file. 
Perhaps grab-site can have an option to generate wacz, I'll suggest that there.

**Comment by ikreymer** [comment]
The latest version includes some fixes to prevent timing out when loading large WARCs (1.3.11), hopefully even on Firefox, so will close this for now. WACZ is still recommended for large WARCs, but I think this is now working as best as possible, given that the entire WARC must be loaded
