### ISSUE TITLE
How do I hide the address bars of the application?

### ISSUE THREAD

**Issue by JeffreyScheffel** [webrecorder/replayweb.page#72]
Sorry if this is the wrong place to ask this type of question but i didn't know where else to go.

Basically I want to hide the website address, local address, client area (file, edit, view etc). 

Is this possible to do? Basically I use this app to teach english from slides I downloaded off a website but the top part makes it too clunky.

![808175050205819733](https://user-images.githubusercontent.com/16633543/139535979-57e6e594-9475-4bbd-855f-052d3254e1e6.jpg)

**Comment by TheTechRobo** [comment]
How did you do it? The embedding thingy doesn't seem to hide the location bar anymore

**Comment by JeffreyScheffel** [comment]
> How did you do it? The embedding thingy doesn't seem to hide the location bar anymore

i was never able to figure it out, if you do lemme know
