### ISSUE TITLE
.WARC file 6.03gb, loading stop at 6% (335mb/6.03gb)

### ISSUE THREAD

**Issue by teddyburberry** [webrecorder/replayweb.page#73]
When I wants to load a .warc file (6.03gb) loading stops at 6%.
With other files, this issue does not occur, but these files weigh less than 6gb
Need help, fast <3

**Comment by DUOLabs333** [comment]
Yeah, the bottleneck is indexing, which is definitely going to be a problem at 6GB. You best choice is to run `pywb`, index it once, and serve it up.

**Comment by ikreymer** [comment]
Duplicate of #67, will continue discussion on loading issues there.
