### ISSUE TITLE
Hosting from subpath breaks navigating some links within archived pages

### ISSUE THREAD

**Issue by wilkie** [webrecorder/replayweb.page#82]
Hello. When I am hosting the static page from a subdirectory and loading from, say, `http://localhost:8989/replayweb.page/index.html`, most behavior seems to work as expected. The only issue I can see is when clicking on a link within the rendered page and having it navigate to another archived page within that archive.

![image](https://user-images.githubusercontent.com/31674/151604388-1a2c0bdf-48c1-4f93-b7cc-4d536aa3a66b.png)

Here, the example '`netpreserve-twitter.warc`' archive has a twitter page preserved that links to the blog post which is preserved. Clicking that link when serving the static pages from root works fine but it breaks when serving off a subpath after it tries to navigate to root when resolving the archive id and reloading. (I also wish it did not load the link in another tab and instead loaded within the iframe... but it doesn't seem to want to do that) I would expect it to resolve to `/<subpath>/?source=blah`, etc, and perhaps not reload.

I'm using Firefox 96 and my copy of Chrome just hangs and crashes when I load that twitter archive at both my local server and the main `replayweb.page` site [using the warc file hosted there](http://replayweb.page/?source=https://replayweb.page/examples/netpreserve-twitter.warc) via 'source' query parameter. I don't know why. 😅

My goals would be to host replayweb.page as some kind of applet within my own web archive project that can embed artifacts in an iframe and it is rather important that it be off of a subpath and not trying to shoehorn my own project's root route. Thanks!

**Comment by ikreymer** [comment]
Hi @wilkie!
I think I understand the issue, you're running an HTTP server from parent dir, and then accessing:
`http://localhost:9899/replayweb.page/?source=/replayweb.page/examples/netpreserve-twitter.warc`

I think I can repro the issue you're seeing with parent dir, will look into that. Probably there's a path somewhere that assumes its at the root.

The recommended way for embedding is to use this approach with the `<replay-web-page>` tag:
https://replayweb.page/docs/embedding (and you can replace the CDN links with local copies of `sw.js` and `ui.js`)
This should work consistently.

**Comment by ikreymer** [comment]
Think it should be fixed! try the `subpath-host` branch, and then will do a fix of wabac.js + replayweb.page

**Comment by ikreymer** [comment]
> I'm using Firefox 96 and my copy of Chrome just hangs and crashes when I load that twitter archive at both my local server and the main `replayweb.page` site [using the warc file hosted there](http://replayweb.page/?source=https://replayweb.page/examples/netpreserve-twitter.warc) via 'source' query parameter. I don't know why. 😅

Have not been able to repro this (maybe redirect loop?), but hopefully it works now.

> My goals would be to host replayweb.page as some kind of applet within my own web archive project that can embed artifacts in an iframe and it is rather important that it be off of a subpath and not trying to shoehorn my own project's root route. Thanks!

Sounds great! I'd recommend using the <replay-web-page> tag approach + either cdn or local hosting.

It can be similar to what we have: https://webarchive-demo2.glitch.me/ but not hosted at the root (should double-check that that works as well)
