### ISSUE TITLE
Content not reachable

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/replayweb.page#9]
Using `warc2zim`, I created a ZIM from a WARC (created using conifere) that you can find at http://tmp.kiwix.org/warc2zim/

There is a styling problem on the iframe that makes the bottom of the pages unreachable and invisible.

Actual content is visible at https://isago.ml

**Comment by ikreymer** [comment]
Thanks for finding that. Turns out it's actually caused by the style of the embed page, it does not need to have a `height: 100%`. For Safari, it does need a `height: -webkit-fill-available;`. I'll fix it in warc2zim.
